### ISSUE TITLE
Segmentation of the dural sac area

### ISSUE THREAD

**Issue by hansbonito** [MuscleMap/MuscleMap#7]
Hello and thank you for a great work. I have tried the script on several samples and it works great on segmenting the paraspinal and psoas muscles. 
My question is, whether there is a way to train the model on segmenting the spinal canal as well, preferably the dural sac cross-sectional area (DSCA, not the bony area)?

 Bestes

**Comment by kennethaweberii** [comment]
@hansbonito Thanks for the feedback, and glad to hear that the paraspinal muscle segmentations are working well for you. That's great. Please let us know if you have any issues. If you can share your data, we can work towards improving the model if there are areas where the performance is suboptimal for your application.

At this time, we are not planning on including the spinal canal segmentation in this model.  Our group also does spinal imaging. For those analyses, we use the Spinal Cord Toolbox (https://github.com/spinalcordtoolbox/spinalcordtoolbox), which is also open-source. The sct_propseg command with -CSF flag does a pretty good job at segmenting the spinal canal.

Thanks again!

**Comment by hansbonito** [comment]
Thanks for the response and for the tip :)
