### ISSUE TITLE
Python 3.9.0 not available through Anaconda on MacOS

### ISSUE THREAD

**Issue by brianwskim** [MuscleMap/MuscleMap#8]
Fantastic work on the project thus far.

When using the Anaconda Distribution, MacOS does not allow for the install of Python Version 3.9.0 when creating a virtual environment with the README's code:
`conda create -n MuscleMap python==3.9.0`

**Message**
Retrieving notices: ...working... done
Channels:
- defaults
Platform: osx-arm64
Collecting package metadata (repodata. json) : done
Solving environment: failed
~ % conda create -n musclemap python==3.9.0
PackagesNotFoundError: The following packages are not available from current channels:
- python==3.9.0
Current channels:
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
To search for alternate channels that may provide the conda package you're looking for, navigate to
https://anaconda.org
and use the search bar at the top of the page.

**Workaround**
However, it does work with the following alternative code:
`conda create -n MuscleMap python=3.9`

MacOS conda seems to accept single '=' with a version to only one decimal place. 

Note: I have trialled uninstalling and reinstalling Anaconda via this [link](https://www.anaconda.com/download/success) for Apple Silicon.

Thank you!

**Comment by kennethaweberii** [comment]
@brianwskim What happens if you try a different version of Python 3.9 such as 3.9.1 or 3.9.2?

Cheers,
Ken

**Comment by brianwskim** [comment]
@kennethaweberii 

After some trial and error, python==3.9.15 and are working with the == equality operator. 

All versions between 3.9.0 and 3.9.14 inclusive are not working with either the assignment = or equality == operators.

Cheers,
Brian

**Comment by kennethaweberii** [comment]
@brianwskim Thanks for reporting the bug. The following works on linux and Windows: conda create -n MuscleMap python=3.9

We will update this in the next release. Thanks!
